### ISSUE TITLE
Consider removing compile.py

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/plugin-test-matrix#32]
The [compile.py](https://github.com/PennyLaneAI/plugin-test-matrix/blob/master/compile.py) file is recommended to be run in the [README](https://github.com/PennyLaneAI/plugin-test-matrix#adding-a-plugin) to create the workflows to be run.

However, we have also [regularly updated workflow](https://github.com/PennyLaneAI/plugin-test-matrix/commits/master/.github/workflows) files directly without using `compile.py` (?). Hence, `compile.py` is likely outdated and may also risk overwriting some of our changes if we run it now.

**Comment by timmysilv** [comment]
just realized this issue exists 😅 I just merged #38 which fixed those workflow files to work with compile.py, AND I added a github action that makes PRs fail if devs try to do something sneaky without `compile.py` to avoid this drift in the future
